### ISSUE TITLE
Handbuch erstellen

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#11]
Wir müssen auch ein Handbuch für die Anwender unseres Tools erstellen.

**Comment by phwachte** [comment]
Der Teil für den Import/Parser liegt in Google Drive unter "Beschreibung CSV-Vorlage für Handbuch".

**Comment by Glur4k** [comment]
Top.

**Comment by Glur4k** [comment]
@Schnullerpip machst du den Teil für die index.php?

**Comment by Glur4k** [comment]
@julmayer machst du die Projektverwaltung? Ist schon auf dem Drive angelegt :wink:

**Comment by Schnullerpip** [comment]
Ja also mein Teil ist ja auch schon aufm drive

**Comment by Glur4k** [comment]
Handbuch liegt im Drive.
