### ISSUE TITLE
Upload-Funktionalität

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#13]
Der Upload von Projektbeschreibungen funktioniert schon.
Die Dateien werden bisher allerdings nur in das PHP temp directory hochgeladen.

Sie müssen nun noch von dort abgeholt und in die Datenbank geschrieben werden.

**Comment by julmayer** [comment]
bin da irgendwie zu bloed dazu.
Hier sieht das ganz einfach aus: http://www.php-mysql-tutorial.com/wikis/mysql-tutorials/uploading-files-to-mysql-database.aspx
Aber ich check nicht was dein ganzes javascript zeug da macht. @Glur4k Vielleicht am besten selber fertig machen oder bei gelegenheit mal erklaeren wo da was ab geht.

**Comment by Glur4k** [comment]
In classes/AjaxHandler/impl/UploadController.php muss anstatt dem move_uploaded_files die Datei in die Datenbank geschrieben werden.
Das Ajax spielt in dem Sinn keine Rolle.

**Comment by Glur4k** [comment]
Ich weise es dir noch mal zu ;D
