### ISSUE TITLE
Weitere Testdaten in "testdaten.sql" anlegen

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#16]
Um die Messreihen-Ansicht zu testen werden weitere Messreihen in der Test-Datenbank benötigt.

**Comment by julmayer** [comment]
Ich würde damit warten bis der Parser funktioniert, dann können wir gleich relaistische Daten importieren.
@phwachte bis wann ist der fertig?

**Comment by julmayer** [comment]
Close da wir jetzt LIve-Daten haben.
