### ISSUE TITLE
Text markieren in Eingabefeldern

### ISSUE THREAD

**Issue by julmayer** [Schnullerpip/EDMA#17]
Wieso kann man Texte in Eingabefelder nicht markieren?
Weder mit der Maus noch mit SHIFT+PFEILTASTE kann ein Text markiert werden.
Die Funktionalität scheint da zu sein, nach STRG+A wir beim Tippen der alte Text überschrieben. Allerdings sieht man visuell nichts.
@Glur4k liegt das irgendwie an CSS?

**Comment by Glur4k** [comment]
Gefixt mit Commit 1ce6ee3
