### ISSUE TITLE
Download Projektbeschreibungen für externe User

### ISSUE THREAD

**Issue by julmayer** [Schnullerpip/EDMA#21]
Externe User sollte die Möglichkeit haben, Projektbeschreibungen herunter zu laden.
Dazu muss entweder eine neue  Seite ähnlich der Projektverwaltung erstellt werden oder die Seite Projektverwaltung muss angepasst werden, sodass externe Benutzer eingeschränkten Zugang dazu haben.

Ich vermute eingeschränkter Zugang ist schneller realisiert.
Dazu muss in header.php das Menü eingeblendet werden und in projekt.php bei "nicht master" alle Felder ausgeblendet/schreibgeschützt werden außer der Liste mit Projektbeschreibungen.

**Comment by Glur4k** [comment]
Ich werde die komplette Liste mit Besucherrechten neu erstellen, ist einfacher als jedes Feld ein-/auszublenden. Ist auch einfacher bezüglich der Lösung des Issues #22 zu lösen.

Wie der Download an sich funktioniert, werde ich damit vorerst nicht lösen. (Ansicht PDF, Download etc., keine Ahnung wie das mit den DB Blobs gemacht wird)
