### ISSUE TITLE
Leeren von InfoModal

### ISSUE THREAD

**Issue by julmayer** [Schnullerpip/EDMA#24]
Aktuell zeigt das InfoModal auch alte Meldungen an.
Beispiel:
Import einer defekten Datei => Errormeldung im InfoModal
Import einer gültigen Datei => Erfolgsmeldung im InfoModal und alte Erromeldung des 1. Import.

**Comment by Glur4k** [comment]
Hoffe das passt

**Comment by phwachte** [comment]
Habs ausgiebig getestet, passt!
Hatte zuerst noch einen Fall, wo das Modal entweder gar nicht mehr oder nur mit größerer Verzögerung angezeigt wurde, obwohl die Messreihe importiert wurde, aber das lag wohl an irgendwas lokal bei mir.
