### ISSUE TITLE
Fehler beim Einloggen

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#28]
Wenn ich mich in ein Projekt einloggen will kommt folgender Fehler:

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\virtual\EDMA\03_System\header.php:143) in C:\xampp\htdocs\virtual\EDMA\03_System\classes\Redirect.php on line 29

bzw:
mal das mal das...

Warning: Creating default object from empty value in C:\xampp\htdocs\virtual\EDMA\03_System\classes\Projekt.php on line 40

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\virtual\EDMA\03_System\header.php:143) in C:\xampp\htdocs\virtual\EDMA\03_System\classes\Redirect.php on line 29

Wenn ich dann aber manuell auf die index.php gehe, bin ich eingeloggt und kann normal weitermachen...

**Comment by phwachte** [comment]
Bei mir ist es genau der gleiche Fall. Ist aber erst seit drei, vier Tagen ungefähr.

**Comment by Glur4k** [comment]
Komisch, die entsprechenden Dateien wurden in letzter Zeit ja nicht geändert.

**Comment by julmayer** [comment]
Sollte durch commit ee8062264887bdec0f3280aa85dbf2b8a1ad1813 behoben sein.
Wir haben die PHP spezifischen Sachen aus dem header.php in den preHeader.php verschoben.
Fehler sollte dadurch gekommen sein, dass im header.php immer schon html (z.b. durch NavBar) uebertragen wurde.
Mich wundert nur, dass der Fehler nicht immer kam weil eigentlich war das ja schon immer so.
Jetzt wird am Anfang der preHeader.php eingebunden und der normale header.php erst, nachdem der Input gehandelt wurde und ein eventueller redirect ausgefuehrt wurde.
