### ISSUE TITLE
Fehlerhafter Zugriff auf Projekt->data

### ISSUE THREAD

**Issue by julmayer** [Schnullerpip/EDMA#29]
Bei projekt.php wird pro Projektbeschreibung auf projekt->data()->id zugegriffen.
Bei neuen Projekten ist dies ein implizierter Zugriff.
Test und beheben.

**Comment by Glur4k** [comment]
Bitte schließen wenn gefixt.

**Comment by julmayer** [comment]
Close by e578aa25eb58474aeeed7b478caa7a5f699c98e9
