### ISSUE TITLE
Keine Messreihen vorhanden

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#36]
Wenn keine Messreihen vorhanden sind soll eine Meldung, statt leere Boxen angezeigt werden.

**Comment by Glur4k** [comment]
Die Meldung bei "Messreihenverwalten" ist eingebaut. (Siehe 590556cc65b540bfc539b030c06622716c14c04d)

@Schnullerpip geht es, dass wenn noch keine Messreihen importiert wurden, auf der Startseite ein Hinweistext statt den Buttons "Metafeld auswählen", "Metafilter hinzufügen" und den Überschriften "Messreihen", "Sensoren" und "Skala" angezeigt wird?

**Comment by Schnullerpip** [comment]
probiers mal aus

**Comment by Schnullerpip** [comment]
sry falscher knopf

**Comment by Schnullerpip** [comment]
done
