### ISSUE TITLE
Default Skala

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#38]
Default-Skala erstellen auf der Startseite.

**Comment by Glur4k** [comment]
Skalen sollten gelöscht und neu erstellt werden können.

**Comment by Glur4k** [comment]
@Schnullerpip wie aufwändig folgendes umzusetzen?

Wenn man einen Sensor auswählt ist automatisch auch die default-Skala ausgewählt?

Das wäre dann perfekt!

**Comment by Glur4k** [comment]
Bei mir funktioniert die Zuweisung nicht mehr? Wenn ich auf Auswählen bei einer Skala drücke wird das Modal geschlossen, aber in der Skala-Spalte wird nichts angezeigt.

**Comment by Glur4k** [comment]
Bitte wenigstens erst antworten bevor man schließt :stuck_out_tongue_winking_eye:

**Comment by Schnullerpip** [comment]
done :)

**Comment by Glur4k** [comment]
Sorry aber den Bug hab ich immer noch... (Siehe Kommentar)

**Comment by Schnullerpip** [comment]
also der name der defaultskala ist "" ich wollte nicht dass es extra bei jedem anzeigt "default skala" sondern wenn es eine selbstgemachte skala ist dann wird sie angeschrieben sonst nicht - die default-skala an sich ist standardmäßig jedem sensor zugewiesen also den graph kannst anzeigen lassen.. im Graphen wird die skala dann auch mit Default Skala betitelt

**Comment by Schnullerpip** [comment]
ist kein bug also ist so gewollt, sonst steht da halt 10 mal default skala fand ich hässlich

**Comment by Schnullerpip** [comment]
also alle anderen skalen werden bei mir immer noch wie vorher angezeigt - auch die defaultskala wird angezeigt heißt aber eben "" weswegen es dann eben nicht sichtbar ist

**Comment by Glur4k** [comment]
Ahso. Aber wenn man eine Skala erstellt steht ja auch nur "Skala: X" da.
Wieso steht dann nicht "Skala: 0" bei der Default-Skala und jede weitere die man hinzufügt fangen dann ab 1 an? 
Find das sonst schon verwirrend wenn bei der Default-Skala nix da steht und bei den "eigenen" schon.

Kleiner Verbesserungsvorschlag allgemein:
Noch besser wärs, wenn dann nicht das Icon und "Skala: X"  in dem Button ist, sondern wenn man eine Skala ausgewählt hat einfach das Icon weg geht und die Zahl der Skala dasteht.

**Comment by Schnullerpip** [comment]
finde es sollte schon klar sichtbar sein was die default skala ist und was nicht

und nur die zahlen anzeigen wären dann find ich ebenfalls verwirrend, dann geht man auf die seite und sieht hinter jedem sensor gleich mal ne "0" und fragt sich aha was sagt mir die null?

**Comment by Glur4k** [comment]
Wie wäre es dann mit einem "d" statt 0? Dann hat man Skala d,1,2,3... Dann ist es klar getrennt.

Initial ist ja schon das Icon da, nur wenn man einen Sensor auswählt wird automatisch die d-Skala ausgewählt und das Icon ersetzt. Somit steht die Skala wenn man auf die Seite geht nie automatisch da, sondern eben erst wenn man einen Sensor gewählt hat.

**Comment by Schnullerpip** [comment]
also kann ich schon machen aber bevor ich dann nur d hinschreib mach ich dann glaub schon default n einfaches d ist auch bloß verwirrend wenn man nicht weiß um was es geht 
sind halt eher so sachen die sind dann klar wenn man des ding zum dritten mal benutzt aber davor kratzt man sich halt auch nur am kopf

**Comment by Glur4k** [comment]
Also ich bin dennoch für ein "d" bzw "D". Steht ja dann im Handbuch drinne was das zu bedeuten hat.
Und wie du sagst, nach 1-2x benutzen reicht die Info völlig ;)
Ist auch dann einheitlicher, als wenn dann "Default, 1,2,3" da steht. (Aus designtechnischen Aspekten ;D)
Positiver Nebeneffekt: die Buttons ziehen sich dann nicht mehr so in die Breite.

**Comment by Schnullerpip** [comment]
gucks dir mal an

**Comment by Glur4k** [comment]
Perfekt.
