### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#39]
Der aktuelle Spinner geht nicht im Chrome.
Der Spinner sollte zudem auch das Chart ausblenden wenn man ein Chart 2x anzeigt.

**Comment by phwachte** [comment]
Spinner läuft jetzt auch in Chrome.

@Glur4k @Schnullerpip : Könnt ihr euch das ausblenden des Charts bei erneutem drücken des Anzeigen-Buttons mal anschauen? Die Funktionalität würde mit meiner Lösung wie gewünscht funktionieren, allerdings zeigt es das Chart-Div dann viel größer an, also der Div passt nicht mehr auf den Bildschirm von der Breite her.
Ich habe meine Änderungen auskommentiert miteingecheckt, damit ihr es auch mal testen könnt. Ist aktuell in der index.php in den Zeilen 1354 ff. und 1444 ff.

**Comment by Glur4k** [comment]
Das Problem war, dass der Wrapper des Charts 100% hatte. Bei aus-und wieder einblenden hat er dann die Breite des Bildschirms bekommen. Da der Inhalt um ca 30% nach Innen verschoben ist wurde das Chart aus dem Bildschirm rausgedrückt.

Habe dem ganzen jetzt die angedachte Bootstrap Struktur gegeben, damit das nicht mehr passiert.

**Comment by Glur4k** [comment]
Tja, also sieht so aus als würde das Probleme mit der Toolbar geben. Ich muss es wieder eröffnen und eine andere Lösung muss gefunden werden.

**Comment by Glur4k** [comment]
Also das Problem ist, dass in $('anzeigeButton').click() die gesamte logik steckt. D.h. das toggeln der elemente wird erst ausgeführt, wenn das Chart fertig ist... Sprich: Nutzlos.

Allerdings habe ich auch keine Lösung des Problems gefunden ohne zu viel zu ändern...
Ich denke wir lassen es einfach so oder?
