### ISSUE TITLE
Master-Passwort ändern

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#42]
Die Seite um das Master-Passwort zu ändern ist erreichbar unter /resetpw.php.
Momentan ist bei uns das Datenbankpasswort leer, also kann dort lokal einfach nichts eingegeben werden.
Live muss dann natürlich das Passwort der Datenbank eingegeben werden.

@phwachte bitte noch in die htaccess mitaufnehmen.
@julmayer, @julmayer, @Schnullerpip bitte mal testen :blush:

Commited in fba6cd4b712fb23898df95899ed075214362f491

**Comment by Schnullerpip** [comment]
ich hab kein reset.php ?

**Comment by Schnullerpip** [comment]
aaah gefunden : resetpw.php

**Comment by Glur4k** [comment]
Sorry, hab's oben verbessert.

**Comment by Glur4k** [comment]
Wenn für gut befunden bitte schließen.
