### ISSUE TITLE
"Cannot read property 'split' of undefined" beim Anzeigen eines Charts

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#43]
![2015-03-12 17_44_58-edma - htwg-konstanz](https://cloud.githubusercontent.com/assets/3889326/6622844/8004edea-c8df-11e4-8a56-164956f56e57.jpg)

Bekomm ich wenn ich alles anzeigen lassen will. Zwei Sensoren ausgewählt.

**Comment by Schnullerpip** [comment]
kanns sein dass du das db skript recreate... noch nicht ausgeführt hast seit flip die mikrosekunden zu nem eigenen feld gemacht hat?

**Comment by Glur4k** [comment]
Hab ich ausgeführt. Beim ersten Mal anzeigen gehts, beim zweiten Mal kommt der Fehler.

**Comment by Glur4k** [comment]
Also hab gemerkt dass recht sporadisch auftritt. Einfach mal paar Sensoren auswählen und anzeigen. Dann andere auswählen und wieder anzeigen. Früh oder später crasht es immer.

**Comment by Schnullerpip** [comment]
hä bei mir nicht...

**Comment by Glur4k** [comment]
Ok dann fürh mal das recreate-script aus und importe die testdaten.
Dann hast du ja nur eine Messreihe. Lass dir von der mal alle Sensoren anzeigen.
Da bekomm ich den Fehler.

**Comment by julmayer** [comment]
also freunde, sieht so aus als ob chartData.php mit den falschen "modus" aufgerufen wird.
Modus = CSV -> Daten sind nur messwert z.B. 0,0001
Modus != CSV -> Daten sind messwert und datum z.B 0,0001;24.12.2014 10:14:00.1234156

Der Fehler den du hast kann eigentilch nur kommen wenn er die falschen daten zurueck bekommt da beim 1. Beispiel (=CSV) kein ';' vorhanden ist und dann hier der Fehler kommt:

var cell = cols[j].split(";");
var datum_uhrzeit = cell[1].split(" ");
werte[j].push([x, parseFloat(cell[0]), datum_uhrzeit[0], datum_uhrzeit[1]]);


Kann im Code aber so nichts erkennen. Machst du zwischenzeitlich ein CSV export oder so?
Importier die Daten die du hast mal im Live system und schau ob du den Fehler dort auch hin bekommst, dann kann man evtl. leichter debuggen.

**Comment by julmayer** [comment]
Oder mach bei dir mal im custom-script in parseCsv ein console.log(csvAsString) und console.log(data)
 data.mode sollte auf jeden fall != CSV sein (vermutlich muesste chart drin stehen)
und csvAsString sollte in der 2. Zeile dann immer tupel aus messwert und date_time haben die durch ; getrennt sind

**Comment by Glur4k** [comment]
![2015-03-13 12_17_00-edma - htwg-konstanz](https://cloud.githubusercontent.com/assets/3889326/6637458/d9b9a0ce-c97a-11e4-801d-147f1e089e57.jpg)

**Comment by Glur4k** [comment]
Console Logs siehe Screeny obendran.

**Comment by Glur4k** [comment]
Neue Info:
Liegt vielleicht daran, dass wenn ein Sensor keine Daten hat?
Habe es nochmal nur mit dem Sensor "Trichter Abluft" probiert, dann kam folgendes:
![2015-03-13 12_26_02-edma - htwg-konstanz](https://cloud.githubusercontent.com/assets/3889326/6637565/246197de-c97c-11e4-9ff6-7dd5d1a62c58.jpg)

Immer wenn ich jetzt ein Chart anzeigen will, bei dem dieser Sensor dabei ist, kommt der Fehler.

**Comment by Schnullerpip** [comment]
Achso :D 
dann machts sinn der split gibt ebenfalls leer zurück und es gibt gar kein cell[1]

**Comment by Schnullerpip** [comment]
man könnte höchstens prüfen ob n sensor keine daten hat und ne meldung werfen aber kommt das wirklich jemals vor in echt?

**Comment by Glur4k** [comment]
Lieber abfangen, statt zu hoffen dass es nicht passiert.
Wenn er keine Daten, hat sollte er halt einfach nicht auftauchen oder?
Oder ein kleiner hinweistext über dem Chart, dass der Sensor X halt keine Daten hat, das Chart aber dennoch anzeigen.

**Comment by Schnullerpip** [comment]
ja ich mein wirklich würde das nicht der parser abfangen und da schon ne meldung geben?

**Comment by Schnullerpip** [comment]
also sogesehen kanns doch garnicht passieren

**Comment by Glur4k** [comment]
@phwachte 
> ja ich mein wirklich würde das nicht der parser abfangen und da schon ne meldung geben?
> - @Schnullerpip

**Comment by julmayer** [comment]
aber das ist komisch. Keine Daten geht eigentlich nicht. Wenn im CSV die Zelle leer ist, muss der Parser das mit 0,0 importieren (war so die Anforderunf weil es Sensoren gibt die bei 100,000 Datensaetzen nur 4 Werte haben).
Also keine Daten zu selektieren geht eigentlich nur, wenn der Zeitraum nicht vorhanden ist. Also von 200,000 bis 300,000 und es sind nur 100,000 Datensaetze oder so.

Hat jemand von euch die Daten mal ins Live System uebertragen damit ich da mal selber schnell schauen kann?

**Comment by Glur4k** [comment]
Kann man live mal ein DB-Reset machen?

Vllt ist das ja nur ein Problem mit den testdaten. Dass dort noch was drin steht, was der Parser nicht generieren kann? Eben nicht das importierte 0,0 o.ä.?

**Comment by julmayer** [comment]
ach verdammt jetzt versteh ich.
Den Fehler den du hast kann in echt nie passieren.
Im Test Projekt hab ich zu dem Messlauf 5 oder 6 sensoren angelegt aber hab nur fuer 3 Sensoren Messungen eingepflegt.
Der Parser wuerde das so nie importieren!
Der Parser importiert die Sensoren die in der "Kopfzeile" vorhanden sind.
Wenn in den Daten-Zeilen weniger Tabs vorhanden sind kommt der Fehler den wir beim Kienzler gesehen haben (gefunden 19 statt 21).
Wenn es von den Tabs her stimmt, importiert der Parser Leere Zellen als 0,0
Dein Fehler kann also nur mit den Testdaten vorkommen. Die sind halt noch nicht fuer Chart anzeigen gedacht :)
Importier einfach eine "eche" CSV und nutz die fuer den Test.

Ist fuer mich ein "won't fix"

**Comment by julmayer** [comment]
Wenn es fuer dich auch ok ist kannst das Ticket zu machen ;)

**Comment by Glur4k** [comment]
Ok alles klar, danke!
