### ISSUE TITLE
Datei zu groß Fehlermeldung

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#44]
Ich weiß, der Fehler sollte eigentlich nicht auftreten, aber wenn eben doch sollte er halt abgefangen werden (Ich hatte den grade, weil die post_max_size bei mir zu niedrig war). 
Kam dann so ein hässlicher englischer Fehler, sollte aber von uns abgefangen werden.

**Comment by phwachte** [comment]
@Glur4k Wie hast du den Fehler bekommen?

**Comment by Glur4k** [comment]
ja genau.

**Comment by phwachte** [comment]
Hast du ne Ahnung, an welcher Stelle ich die POST-size ermitteln kann? Müsste das im UploadController gehen? 
Bzw wäre es so wichtig das abzufangen, wenn es wie du selbst sagst, unwahrscheinlich ist, dass solche Fehler auftreten? Dann müsste man nämlich auch die alloc-Fehler abfangen und die execution_time-Fehler und so weiter.

**Comment by Glur4k** [comment]
Naja, mir ists egal. Wollte es nur mal in die Runde werfen.

Wäre dann im UploadController. Evtl im Konstruktor.
