### ISSUE TITLE
Settings PHP.ini Live

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#45]
Einstellungen die auf dem Live-Server gesetzt werden müssen:

```
upload_max_filesize=128M
post_max_size=128M
```

**Comment by phwachte** [comment]
Bei mir muss auch memory_limit erhöht werden. Bei mir haben 256M (wohl knapp) nicht ausgereicht bei der einen großen Datei, hab es mal auf 512M gesetzt.

**Comment by phwachte** [comment]
Die Variablen müssten ja alle lokal gesetzt haben, auf messwik wurde es ebenfalls angepasst, daher closed.
