### ISSUE TITLE
Upload funktioniert nicht!!!!

### ISSUE THREAD

**Issue by Schnullerpip** [Schnullerpip/EDMA#46]
Flip und ich wollen grade die präsi planen und es scheitert schon am upload der projektbeschreibung....
![screenshot from 2015-03-17 12 35 51](https://cloud.githubusercontent.com/assets/3928616/6686520/888e6614-cca2-11e4-913f-ba59b0e6adb8.png)

**Comment by julmayer** [comment]
Kerle steht doch da. Musst dein System halt richtig konfigurieren.
Im 03_System/uploads braucht dein lampp Schreibrechte um einen tmp ordner zu erstellen und die Files zu speichern.
Wenn du den User nicht kennst dann unter Windows einfach Rechte fuer Benutzer "Jeder" vergeben
