### ISSUE TITLE
Projekt hinzufügen Funktionalität

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#8]
Beim Hinzufügen eines neues Projektes ist die ID des Projektes noch "null".
Beim Absenden des Formulars soll das Projekt in der Datenbank angelegt werden.
Danach soll man das Projekt als master angemeldet werden und auf die index.php weitergeleitet werden.

Achtung beim Upload der Projektbeschreibung! Diese liegt beim Upload im temporary directory von PHP und kann erst in die Datenbank geschrieben werden, wenn die ID des Projektes bekannt ist, also nach dem erfolgreichen Erstellen dessen.

**Comment by julmayer** [comment]
Teil 1 Funktioniert durch Commit 8ad576e.
Upload der Projektbeschreibung muss noch implementiert und getestet werden.

**Comment by Glur4k** [comment]
Wenn man ein neues Projekt hinzufügt und dann allerdings auf "Abbrechen" klickt scheint er nicht abzubrechen. Man wird dennoch auf die index Seite weitergeleitet und bekommt einen error angezeigt.
