### ISSUE TITLE
Test Datenbankqueries in Doku anlegen

### ISSUE THREAD

**Issue by Glur4k** [Schnullerpip/EDMA#9]
Exemplarische Queries definieren.

Z.B. 
Hole letzte 5 Messreihen des Projektes mit der ID = x
Hole alle Metadaten des Projektes mit der ID = x
Hole alle Sensoren der Messreihe mit der ID x und der Metainfo Datum = dd.mm.yyyy und der Metainfo Material = LEGO

Ebenso für Updates oder Inserts.

usw.

**Comment by julmayer** [comment]
-- hole die letzten 5 messreihen zu projekt mit id 1
SELECT * FROM messreihe WHERE `projekt_id` = 1 ORDER BY datum DESC LIMIT 5;

-- hole alle metainfos zu alle messreihen von projekt mit id 1
SELECT messreihe.messreihenname, metainfo.metaname, messreihe_metainfo.metawert FROM metainfo 
  INNER JOIN messreihe_metainfo ON metainfo.id = messreihe_metainfo.metainfo_id
  INNER JOIN messreihe ON messreihe_metainfo.messreihe_id = messreihe.id
  WHERE messreihe.projekt_id = 1;
  

-- holle alle sensoren der messreihen zu projekt mit id 1 von messreihen vom 14.10.2014 mit Material = PA6
SELECT sensor.* FROM sensor
  WHERE EXISTS (SELECT 5 FROM messung 
                        INNER JOIN messreihe on messung.messreihe_id = messreihe.id 
                        INNER JOIN messreihe_metainfo on messreihe.id = messreihe_metainfo.messreihe_id
                        INNER JOIN metainfo on messreihe_metainfo.metainfo_id = metainfo.id
                        WHERE messung.sensor_id = sensor.id 
                          AND messreihe.projekt_id = 1
                          AND messreihe.datum = '2014-10-14'
                          AND metainfo.metaname = 'Material'
                          AND messreihe_metainfo.metawert = 'PA6');
  

-- alternative ohne exists
SELECT sensor.* FROM sensor
  INNER JOIN messung on sensor.id = messung.sensor_id
  INNER JOIN messreihe on messung.messreihe_id = messreihe.id
  INNER JOIN messreihe_metainfo on messreihe.id = messreihe_metainfo.messreihe_id
  INNER JOIN metainfo on messreihe_metainfo.metainfo_id = metainfo.id
  WHERE messreihe.projekt_id = 1
    AND messreihe.datum = '2014-10-14'
    AND metainfo.metaname = 'Material'
    AND messreihe_metainfo.metawert = 'PA6'
  GROUP BY id, sensorname;

updates und inserts sind bei uns eigentlich ziemlich trivial, denke nicht das man da Beispiele braucht. Ich kann da aber immer gerne helfen wenn jemand was explizites hat. Wir koennen ja einfach dafuer dieses Ticket offen lassen.

**Comment by Glur4k** [comment]
Hab mal ne Seite in der Doku angelegt:
https://github.com/Schnullerpip/EDMA/wiki/Beispiel-Datenbankqueries

**Comment by Glur4k** [comment]
Kannst du bitte ein Query machen für:
**Hole alle Metadaten zu einer Messreihe**

**Comment by julmayer** [comment]
SELECT metainfo.metaname, messreihe_metainfo.metawert FROM metainfo INNER JOIN messreihe_metainfo ON metainfo.id = messreihe_metainfo.metainfo_id WHERE messreihe_metainfo.messreihe_id = X

**Comment by julmayer** [comment]
wenn es was neues gibt wieder Oeffnen
